Bag Of Words(BOW)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('spam_data.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [5]:
print(df.shape)
df.head()

(5572, 3)


Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2)

In [7]:
X_train.shape

(4457,)

In [8]:
X_test.shape

(1115,)

In [9]:
X_train.head()

4221    U free on sat rite? U wan 2 watch infernal aff...
2838                              1's reach home call me.
762     We are at grandmas. Oh dear, u still ill? I fe...
2194    I called but no one pick up e phone. I ask bot...
3238    Ron say fri leh. N he said ding tai feng cant ...
Name: Message, dtype: object

In [10]:
y_train.head()

4221    0
2838    0
762     0
2194    0
3238    0
Name: Spam, dtype: int64

Bag of Words using CountVectorizer

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_test_cv=v.transform(X_test)
X_train_cv

<4457x7773 sparse matrix of type '<class 'numpy.int64'>'
	with 59437 stored elements in Compressed Sparse Row format>

In [12]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
X_train_cv.shape

(4457, 7773)

In [14]:
v.get_feature_names_out()[2673]

'every'

In [15]:
v.vocabulary_

{'free': 2983,
 'on': 4934,
 'sat': 5923,
 'rite': 5803,
 'wan': 7395,
 'watch': 7419,
 'infernal': 3675,
 'affairs': 840,
 'wif': 7534,
 'me': 4414,
 'darren': 2184,
 'mayb': 4406,
 'xy': 7687,
 'reach': 5595,
 'home': 3477,
 'call': 1614,
 'we': 7438,
 'are': 1049,
 'at': 1115,
 'grandmas': 3218,
 'oh': 4911,
 'dear': 2207,
 'still': 6504,
 'ill': 3615,
 'felt': 2812,
 'shit': 6117,
 'this': 6879,
 'morning': 4593,
 'but': 1582,
 'think': 6871,
 'am': 935,
 'just': 3880,
 'hungover': 3553,
 'another': 981,
 'night': 4778,
 'then': 6851,
 'leave': 4066,
 'called': 1621,
 'no': 4796,
 'one': 4939,
 'pick': 5203,
 'up': 7211,
 'phone': 5190,
 'ask': 1093,
 'both': 1451,
 'of': 4893,
 'them': 6847,
 'already': 925,
 'they': 6864,
 'said': 5890,
 'ok': 4916,
 'ron': 5824,
 'say': 5940,
 'fri': 3000,
 'leh': 4078,
 'he': 3365,
 'ding': 2335,
 'tai': 6705,
 'feng': 2814,
 'cant': 1650,
 'make': 4332,
 'reservations': 5735,
 'wait': 7378,
 'lor': 4213,
 'and': 961,
 'several': 6060,
 'to': 6

In [19]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
np.where(X_train_np[0]>0)

(array([ 840, 2184, 2983, 3675, 4406, 4414, 4934, 5803, 5923, 7395, 7419,
        7534, 7687], dtype=int64),)

In [22]:
X_train[:4][4221]

'U free on sat rite? U wan 2 watch infernal affairs wif me n darren n mayb xy?'

In [24]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)


MultinomialNB()

In [27]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       969
           1       0.97      0.90      0.93       146

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [28]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)